name: Dolomite
icon: logo.png
category: Money Market
url: https://app.dolomite.io/balances
description: >-
  Dolomite is a next-generation decentralized money market protocol and 
  DEX that offers broad token support and capital efficiency with its virtual liquidity system.