name: InsurACE
icon: logo.png
category: Insurance
description: >-
  The InsurAce Protocol is a leading decentralized multi-chain protocol that provides reliable, 
  robust and secure risk protection services to DeFi users, allowing them to protect their investment funds against various risks.