name: Index Coop
icon: logo.png
metadata:
  pt:
    - chainId: 1
      address: '0xf7906F274c174A52d444175729E3fa98f9bde285'
      integrationUrl: https://indexcoop.com/products/high-yield-eth
      description: >-
        High Yield ETH (hyETH) is a diversified index targeting the highest
        ETH-denominated yields on Ethereum Mainnet
    - chainId: 1
      address: '0x6ee2b5E19ECBa773a352E5B21415Dc419A700d1d'
      integrationUrl: https://indexcoop.com/products/high-yield-eth
      description: >-
        High Yield ETH (hyETH) is a diversified index targeting the highest
        ETH-denominated yields on Ethereum Mainnet
    - chainId: 1
      address: '0x1c085195437738d73d75DC64bC5A3E098b7f93b1'
      integrationUrl: https://indexcoop.com/products/high-yield-eth
      description: >-
        High Yield ETH (hyETH) is a diversified index targeting the highest
        ETH-denominated yields on Ethereum Mainnet
  yt: []
  lp: []
