name: Lista Lending
icon: logo.png
category: Money Market
url: 'https://lista.org/lending'
description: 'Redefining BNB with Liquid Staking, Lista Lending and CDP Solutions'
metadata:
  pt:
    - chainId: 56
      address: '0x9e9093a12b343c0f4d519ab093bef989b1936f73'
      integrationUrl: >-
        https://lista.org/lending/market/bsc/0xa6af85dea0813e101ec35ba9e83b23c33583c85734f566eef842e1f4af3a070c
      description: >-
        PT-stcUSD-23JUL2026 can be used as collateral to borrow or multiply
        against USDT
      subtitle: USDT
    - chainId: 56
      address: '0x1e798c7fce8b3cdce8950f8ff5a0c62f1dc7d532'
      integrationUrl: >-
        https://lista.org/lending/market/bsc/0x0ea1212e590eb38d2cd646faabe1dcb5ec1aaebff39701f2a3558399b44397a6
      description: >-
        PT-sUSDai-15OCT2026 can be used as collateral to borrow or multiply
        against USDT
      subtitle: USDT
    - chainId: 56
      address: '0x54a8f370575fe98c305640d7d11b8aa2df451b13'
      integrationUrl: >-
        https://lista.org/lending/market/bsc/0xa44adcc94ded8fe976419e3ebb4fe149b9cdec4893e870eecb46541b11099268
      description: >-
        PT-reUSD-25JUN2026 can be used as collateral to borrow or multiply
        against USDT
      subtitle: USDT
    - chainId: 56
      address: '0x4aa18834211fb3e2b6cbd14b5e22b33c2c0475c2'
      integrationUrl: >-
        https://lista.org/lending/market/bsc/0xa9e70c1d4853fe8125e8d25d785acf3f9f9adf9f2a65203e0e798f5cce991751
      description: >-
        PT-USDG-28MAY2026 can be used as collateral to borrow or multiply
        against USDT
      subtitle: USDT
  yt: []
  lp: []
