name: Lista Lending
icon: logo.png
category: Money Market
url: https://lista.org/lending
description: Redefining BNB with Liquid Staking, Lista Lending and CDP Solutions
metadata:
  pt:
    - chainId: 56
      address: '0x67e84ba0196738a59ee58df848a2c16ed2a6a6f3'
      integrationUrl: >-
        https://lista.org/lending/market/bsc/0xdee403936c6f4c64095e68301c0b5ea2d49fa36ed204b61d504f55b280079a36
      description: >-
        PT-USDe-9APR2026 can be used as collateral to borrow or multiply against
        USD1
      subtitle: USD1
  yt: []
  lp: []
