name: Binance
icon: logo.png
category: CEX / Web3 Wallet
url: https://www.binance.com/en/binancewallet
description: >-
  Binance is the largest cryptocurrency exchange by trading volume, serving 185M+ usrs across 180+ countries.