name: Timeswap
icon: logo.png
metadata:
  pt:
    - chainId: 42161
      address: '0x2Be6Fab4d1408e7ad6AD91cE7B77FA2A7670782f'
      integrationUrl: https://app.timeswap.io/lend/3ddff11d-768c-4b3a-8617-264be2dca259
      description: PT non-liquidatable leverage through Timeswap
    - chainId: 1
      address: '0xAE5099C39f023C91d3dd55244CAFB36225B0850E'
      integrationUrl: https://app.timeswap.io/borrow/ec9a953a-1e4c-44b7-9030-49c7596b4ee3
      description: PT non-liquidatable leverage through Timeswap
    - chainId: 5000
      address: '0x1333B49BBdD06544a25647f9127358D9A9486105'
      integrationUrl: https://app.timeswap.io/borrow/f0485775-7de2-49b3-8c59-a006627715a0
      description: PT non-liquidatable leverage through Timeswap
    - chainId: 5000
      address: '0x8be66A48EA1f4AFF89cd2beb50B02D901Dfb9584'
      integrationUrl: https://app.timeswap.io/lend/64a46623-eed1-40e8-9c3f-273a5cc48512
      description: PT non-liquidatable leverage through Timeswap
  yt: []
  lp: []
