name: OKX
icon: logo.png
category: CEX / Web3 Wallet
url: https://web3.okx.com/defi
description: >-
  OKX is a global company offering exchange and Web3 services with 
  offices in Hong Kong, Singapore, the UAW, Silicon Valley and the Bahamas.