name: OKX
icon: logo.png
category: CEX / Web3 Wallet
description: >-
  OKX is a global company offering exchange and Web3 services with 
  offices in Hong Kong, Singapore, the UAW, Silicon Valley and the Bahamas.