name: Spark
icon: logo.png
category: Money Market
url: https://spark.fi/
description: >-
  Spark is on a mission to empower the DAI ecosystem by building
  DeFi infrastructure such as SparkLend, SparkConduits and supporting DAI.