name: YieldFi
icon: logo.png
category: Yield Strategy
description: YieldFi helps you earn higher returns on your cryptocurrency investments through yield farming, staking, and liquidity provision.
metadata:
  pt:
    - chainId: 1
      address: '0xf10a134a987e22ffa9463570a6d1eb92a63fc178'
      integrationUrl: 'https://yield.fi/mint'
      description: 'PT_csUSDL-31_JUL_2025 is the asset used as collateral to mint yUSD. You can borrow or leverage loop against yUSD perpetually with USDC as loan asset.'
    - chainId: 1
      address: '0xab365c0879024481e4ad3b47bd6fea9c10014fbc'
      integrationUrl: 'https://yield.fi/mint'
      description: 'PT_sUSDF-25_SEP_2025 is the asset used as collateral to mint yUSD. You can borrow or leverage loop against yUSD perpetually with USDC as loan asset.'
    - chainId: 1
      address: '0x7f01d0fce9bc646389483384c41b4d71c7139f11'
      integrationUrl: 'https://yield.fi/mint'
      description: 'PT_mEDGE-31_JUL_2025 is the asset used as collateral to mint yUSD. You can borrow or leverage loop against yUSD perpetually with USDC as loan asset.'
    - chainId: 1
      address: '0x933b9ffee0ad3ef8e4dbb52688ea905826d73755'
      integrationUrl: 'https://yield.fi/mint'
      description: 'PT_cUSDO-19_JUN_2025 is the asset used as collateral to mint yUSD. You can borrow or leverage loop against yUSD perpetually with USDC as loan asset.'
  yt: []
  lp: []
