name: Pichi
icon: logo.png
category: Others
metadata:
  pt:
    - chainId: 1
      address: '0xf7906F274c174A52d444175729E3fa98f9bde285'
      integrationUrl: https://app.pichi.finance/
      description: Deposit PT into a Pichi Wallet to earn points and trade trustlessly
    - chainId: 1
      address: '0x6ee2b5E19ECBa773a352E5B21415Dc419A700d1d'
      integrationUrl: https://app.pichi.finance/
      description: Deposit PT into a Pichi Wallet to earn points and trade trustlessly
  yt:
    - chainId: 1
      address: '0x7749F5Ed1e356EDc63D469c2fcaC9adEB56d1C2b'
      integrationUrl: https://app.pichi.finance/
      description: Deposit YT into a Pichi Wallet to earn points and trade trustlessly
    - chainId: 1
      address: '0x129e6B5DBC0Ecc12F9e486C5BC9cDF1a6A80bc6A'
      integrationUrl: https://app.pichi.finance/
      description: Deposit YT into a Pichi Wallet to earn points and trade trustlessly
  lp:
    - chainId: 1
      address: '0x7d372819240d14fb477f17b964f95f33beb4c704'
      integrationUrl: https://app.pichi.finance/
      description: Deposit LP into a Pichi Wallet to earn points and trade trustlessly
    - chainId: 1
      address: '0xd8f12bcde578c653014f27379a6114f67f0e445f'
      integrationUrl: https://app.pichi.finance/
      description: Deposit LP into a Pichi Wallet to earn points and trade trustlessly
