name: AFI
icon: logo.png
category: Yield Strategy
url: https://www.afiprotocol.ai/
description: >-
  AFI builds Proof-of-Reserve infrastructure for Real-World Assets, unlocking institutional-grade yield that’s fully composable in DeFi.
