name: DeFi Saver
icon: logo.png
category: Yield Strategy
url: https://app.defisaver.com/
description: >-
  DeFi Saver is an all-in-one management tool for DeFi protocols such as Aave, Compound, Fluid, Morpho, Sky and more.
