name: Origami
icon: logo.png
category: Yield Strategy
metadata:
  pt:
    - chainId: 1
      address: '0xae5099c39f023c91d3dd55244cafb36225b0850e'
      integrationUrl: >-
        https://origami.finance/vaults/1-0xb9dad3693AEAc9025Cb24a47AFA6930539877187/info
      description: A 5x leveraged position on PT sUSDe OCT 2024
  yt: []
  lp: []
