name: Gate.io
icon: logo.png
category: CEX / Web3 Wallet
description: >-
  Established in 2013, Gate.io has consistently ranked among the top 10 exchanges. 
  It is a full-service digital asset exchange platform covering million of users around the world