name: Bybit
icon: logo.png
category: CEX / Web3 Wallet
url: https://www.bybit.com/en/web3/staking
description: >-
  Bybit is the world’s 2nd largest cryptocurrency exchange by trading volume. 
  Established in March 2018, Bybit currently serves more than 40 million users and institutions.