name: Morpho
icon: logo.png
category: Money Market
url: 'https://app.morpho.org/ethereum/borrow'
description: >-
  A permissionless and non-custodial lending protocol where users can earn
  interest on over-collaterized lending and borrow digital assets using
  immutable infrastructure.
metadata:
  pt:
    - chainId: 1
      address: '0x928fb6ed39100a92b2480f5cbb93453f98d9f4ce'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0x702b7ec7628de2622e51e1bb34a7e6ad9e95f3a25a2ed361e4ce621f23f5e642
      description: >-
        The PT-cUSD-23JUL2026 is the asset used as collateral in a Morpho market
        with USDC as the loan token.
    - chainId: 1
      address: '0x928fb6ed39100a92b2480f5cbb93453f98d9f4ce'
      subtitle: USDT
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0xfd039edc69eac5eaab4a10463fdbcaca75d6eddb1f0e00248d73fc977fb2554b
      description: >-
        The PT-cUSD-23JUL2026 is the asset used as collateral in a Morpho market
        with USDT as the loan token.
    - chainId: 1
      address: '0x2d3c279e5fcdf5b793c0a75ed90738d7369b0b83'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0x2fb3713487c7812e7309935b034f40228841666f6b048faf31fd2110ae674f20
      description: >-
        The PT-stcUSD-23JUL2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0x2d3c279e5fcdf5b793c0a75ed90738d7369b0b83'
      subtitle: USDT
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0x5eaaebc81e9e27972ab458811d1b60828e8ab51ef6620f9b3918fd7e68eecec1
      description: >-
        The PT-stcUSD-23JUL2026 is the asset used as collateral in a Morpho
        market with USDT as the loan token.
    - chainId: 1
      address: '0x1d69402390657308c91179aa184bf992908c1e08'
      subtitle: AUSD
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0x9464b3d42133c10c8b216d3d9429b43e98c2f3856a87940ef18b8bdd3e7bd831
      description: >-
        The PT-USDat-27AUG2026 is the asset used as collateral in a Morpho
        market with AUSD as the loan token.
    - chainId: 1
      address: '0x1d69402390657308c91179aa184bf992908c1e08'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0x69ef7fd17b42cd7df6d885aee1b11380837afbc1664b25587041cf193b31617b
      description: >-
        The PT-USDat-27AUG2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0x2d433b943fb8c015ae409444b7f960ed288082b4'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0x42c2b592fc759fad461fb5c80d5ea214a496f70d8594398d69af68c2f3798de6
      description: >-
        The PT-srUSDat-27AUG2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 130
      address: '0x9d9874e867b877dd0a3f1eafb8bb1bc54eecc682'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/unichain/market/0x87a686cc100aabe917f8e1ad58140a1b63f0edbb9650a32c0526718dc610b2d5
      description: >-
        The PT-cUSD-23JUL2026-(ETH) is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0xd341a146a4fd20ea89898e4d86ae1829bf3a1c23'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0xf02d2e8f427a2b91785b3d09690ef9d3811bf674ba97b00bafc7665004a6dd97
      description: >-
        The PT-sUSDD-27AUG2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0xb5be35d8ff83d431899b95851cb17a2b4bcef150'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0xb37c30f34bff11c81ee8400133965f450a5f7c5d81ba2cf5740076f49eabc95c
      description: >-
        The PT-apyUSD-5NOV2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0xaf687b5ecb525ccea96115088999b4ed80c388b6'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0x908b037029b5c0671ba3b362eaf289c3199560d1d4632e6cb527cc7240fa006e
      description: >-
        The PT-apxUSD-5NOV2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0x7f47c3e6b2c00fc4eb4d5ae50d0ab0ab6888eb4d'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0xf8c5aa31ea6b2a068a9eddb46dd110cae57bf0f12be9583a3f9a818effecba89
      description: >-
        The PT-USD3-17DEC2026 is the asset used as collateral in a Morpho market
        with USDC as the loan token.
    - chainId: 1
      address: '0xd341a146a4fd20ea89898e4d86ae1829bf3a1c23'
      subtitle: USDT
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0xdf6ca97d41975a6996e9db491cb38152b65d7c00807dfe15d95d8d76e5d122e0
      description: >-
        The PT-sUSDD-27AUG2026 is the asset used as collateral in a Morpho
        market with USDT as the loan token.
    - chainId: 1
      address: '0xc689f76f90fe1762fac55983ff25ae71033a84f7'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0x4bb22a5f6313fc9d7b5e1438967bfcd0a513a839d26662dd8d235629942400e2
      description: >-
        The PT-sUSDat-27AUG2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0x5a19fa369f2895dcd8d2cee62e4ceae58ef92bbb'
      subtitle: RLUSD
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0x1749e02006bc6bd6a86af52d231511f6911d5e42318e028e51a28dfabc68dd47
      description: >-
        The PT-sUSDE-13AUG2026 is the asset used as collateral in a Morpho
        market with RLUSD as the loan token.
    - chainId: 1
      address: '0xecfafdc7741323a945a163ed068b5a3c43483957'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0x1e9d614631a7df0ec07fb05b2c8cb2491575fd1a63a33bf187a6afb295a4fc64
      description: >-
        The PT-reUSD-10DEC2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0xc1906aecf868749a2dee203f59b904c0cf212140'
      subtitle: USDT
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0x02bb03bf55f07c3ed3eee8a25d8df60fb9d09a38db612f0e07cf5c4d3df0100d
      description: >-
        The PT-USDG-24SEP2026 is the asset used as collateral in a Morpho market
        with USDT as the loan token.
    - chainId: 1
      address: '0xee5c7cda577484b70b65c21235ecbd302bb290e2'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0x62878115c6ee109c256237eb6daef589d006258202682d2e210cad3bb19e0f09
      description: >-
        The PT-apyUSD-27AUG2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0xd28b0d694b8e814fa905a8b480b30691e18396eb'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0x4483b864209c50da2be8fc75371db0e92fdc6bc8920d86fc9b56ea7383f8c9d1
      description: >-
        The PT-apxUSD-27AUG2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0xb5be35d8ff83d431899b95851cb17a2b4bcef150'
      subtitle: apxUSD
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0xebd23a871b52e0a8c92bd719f4413600101b69e946cb72923b3a33fb5bc6ec85
      description: >-
        The PT-apyUSD-5NOV2026 is the asset used as collateral in a Morpho
        market with apxUSD as the loan token.
    - chainId: 1
      address: '0xaf687b5ecb525ccea96115088999b4ed80c388b6'
      subtitle: apxUSD
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0xd86df29b48f2d88a0453027212247a29e68ff52c6589c46054f57285da2fa7e3
      description: >-
        The PT-apxUSD-5NOV2026 is the asset used as collateral in a Morpho
        market with apxUSD as the loan token.
  yt: []
  lp: []
