name: Morpho
icon: logo.png
category: Money Market
url: 'https://app.morpho.org/ethereum/borrow'
description: >-
  A permissionless and non-custodial lending protocol where users can earn
  interest on over-collaterized lending and borrow digital assets using
  immutable infrastructure.
metadata:
  pt:
    - chainId: 1
      address: '0xb5be35d8ff83d431899b95851cb17a2b4bcef150'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0xb37c30f34bff11c81ee8400133965f450a5f7c5d81ba2cf5740076f49eabc95c
      description: >-
        The PT-apyUSD-5NOV2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0xaf687b5ecb525ccea96115088999b4ed80c388b6'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0x908b037029b5c0671ba3b362eaf289c3199560d1d4632e6cb527cc7240fa006e
      description: >-
        The PT-apxUSD-5NOV2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0x7f47c3e6b2c00fc4eb4d5ae50d0ab0ab6888eb4d'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0xf8c5aa31ea6b2a068a9eddb46dd110cae57bf0f12be9583a3f9a818effecba89
      description: >-
        The PT-USD3-17DEC2026 is the asset used as collateral in a Morpho market
        with USDC as the loan token.
    - chainId: 1
      address: '0xecfafdc7741323a945a163ed068b5a3c43483957'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0x1e9d614631a7df0ec07fb05b2c8cb2491575fd1a63a33bf187a6afb295a4fc64
      description: >-
        The PT-reUSD-10DEC2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0xb5be35d8ff83d431899b95851cb17a2b4bcef150'
      subtitle: apxUSD
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0xebd23a871b52e0a8c92bd719f4413600101b69e946cb72923b3a33fb5bc6ec85
      description: >-
        The PT-apyUSD-5NOV2026 is the asset used as collateral in a Morpho
        market with apxUSD as the loan token.
    - chainId: 1
      address: '0xaf687b5ecb525ccea96115088999b4ed80c388b6'
      subtitle: apxUSD
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0xd86df29b48f2d88a0453027212247a29e68ff52c6589c46054f57285da2fa7e3
      description: >-
        The PT-apxUSD-5NOV2026 is the asset used as collateral in a Morpho
        market with apxUSD as the loan token.
    - chainId: 42161
      address: '0xc9d24ad0bb25f34098e226a8c5192dea7bacccae'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/arbitrum/market/0x97cb4b88a7a5e8e9c039b106374124e642395437ffc0ef93f2799343ad022985
      description: >-
        The PT-USDai-15OCT2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 143
      address: '0x9fc74f8ed616b5baf52a170caa97d6d3898602d1'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/monad/market/0x93a7a013b5501cee5d9bee0d29bb3fca790196134c4c7058365e5bc6d2ad80a2
      description: >-
        The PT-AUSD-8OCT2026 is the asset used as collateral in a Morpho market
        with USDC as the loan token.
    - chainId: 1
      address: '0xecfafdc7741323a945a163ed068b5a3c43483957'
      subtitle: USDT
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0x6acd18854e43f93f5a90446004c35c72a68af1ad99f08cb247782ce6457914ca
      description: >-
        The PT-reUSD-10DEC2026 is the asset used as collateral in a Morpho
        market with USDT as the loan token.
    - chainId: 143
      address: '0x9fc74f8ed616b5baf52a170caa97d6d3898602d1'
      subtitle: mUSD
      integrationUrl: >-
        https://app.morpho.org/monad/market/0x71cad28b047d94c5a57c947619f9790b06b121536f975e03fdf241e9316edec7
      description: >-
        The PT-AUSD-8OCT2026 is the asset used as collateral in a Morpho market
        with mUSD as the loan token.
    - chainId: 1
      address: '0xc1906aecf868749a2dee203f59b904c0cf212140'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0x2412afc9614939a5d994397fe0b94a4f6fb8bc02bfc139e1a5956a865e2efe26
      description: >-
        The PT-USDG-24SEP2026 is the asset used as collateral in a Morpho market
        with USDC as the loan token.
    - chainId: 999
      address: '0x50fc4edc6346f36993bb30fe60e932504ed17391'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/hyperevm/market/0xbdceb93661a9efbd67f97ff2842d159a493f792e71f762c8ba426b586dc1c565
      description: >-
        The PT-kHYPE-24SEP2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0xdc169abe56461a2e0c034da431ac2a3ebf596094'
      subtitle: USDS
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0x9a8dab6de1059e6dc66c34b358764b70effb289e514e237f3161ffb09eaaf24f
      description: >-
        The PT-sUSDS-26NOV2026 is the asset used as collateral in a Morpho
        market with USDS as the loan token.
    - chainId: 1
      address: '0x74299580811e1c3c1a2831db079ba0a8f513998f'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0xf062a110320da27e0e7e7d9e1bdf458dd51e2d2089e55f63ff9fd54f415ce35d
      description: >-
        The PT-strUSD-26NOV2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0xdc169abe56461a2e0c034da431ac2a3ebf596094'
      subtitle: USDT
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0x0367161b7cb23dfd03747dd3815d1c445b0437b648a6d50346249c6e7b92ff1b
      description: >-
        The PT-sUSDS-26NOV2026 is the asset used as collateral in a Morpho
        market with USDT as the loan token.
    - chainId: 1
      address: '0xdc169abe56461a2e0c034da431ac2a3ebf596094'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0x22fe4c688161863c73571a2b8db65cc11a4a6bceee4f0dea4aa83e4b784f1bd9
      description: >-
        The PT-sUSDS-26NOV2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0x7191878f1fe834b28f4d0cead0e4375b814c4abb'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0xd21bbc238918855461d943753ac4c90d103888e5661fd78f3378294c45f7d8df
      description: >-
        The PT-trUSD-26NOV2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0xc1906aecf868749a2dee203f59b904c0cf212140'
      subtitle: USDT
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0x02bb03bf55f07c3ed3eee8a25d8df60fb9d09a38db612f0e07cf5c4d3df0100d
      description: >-
        The PT-USDG-24SEP2026 is the asset used as collateral in a Morpho market
        with USDT as the loan token.
    - chainId: 143
      address: '0xa08a69ab9dd3b04d0992bc7afb2c0b907bbdc147'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/monad/market/0x093bd94086b08a013c96dc0776ebf663e9300e742a2c14479211cc35da6c3439
      description: >-
        The PT-USDat-14JAN2027 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 143
      address: '0xdaf216939826acaba0c2312f7e30a890213845cd'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/monad/market/0xcd6d902d2d214c0a06785a072b94b4f3a4fd3ddfa6f6e6861807964ea78cdf98
      description: >-
        The PT-earnAUSD-8OCT2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0xba96292ee7673e3b546cc90db6d97111cd9a314f'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0xc7e49dd404825da16988955201ed22ecf8a7b25f0337db8a698d70d7a9f343ea
      description: >-
        The PT-USDat-14JAN2027 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0x0b985c624bb2949432cce77cfd246f01390a0517'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0x7fb1a1db36cc77c1488cd79915ce05ee56c8d256515c20caae926ba74edc4687
      description: >-
        The PT-sUSDat-14JAN2027 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0xb195b618ea52b77cb2a58846f452f59f8dfa9390'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0x5613b170ded221c588b6e9637b910f49e5508680ceede207f44aa72e5c46cb05
      description: >-
        The PT-sUSDE-26NOV2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 143
      address: '0x355e82c60d51d6942bdfd0f2b95a204acd068963'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/monad/market/0x08d20c5fcb86795781fd940cdc6e7fac864e9b0318d91d73b3ca360844378651
      description: >-
        The PT-srUSDat-14JAN2027 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
  yt: []
  lp: []
