name: Morpho
icon: logo.png
category: Money Market
url: https://app.morpho.org/ethereum/borrow
description: >-
  A permissionless and non-custodial lending protocol where users can earn
  interest on over-collaterized lending and borrow digital assets using
  immutable infrastructure.
metadata:
  pt:
    - chainId: 1
      address: '0x928fb6ed39100a92b2480f5cbb93453f98d9f4ce'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0x702b7ec7628de2622e51e1bb34a7e6ad9e95f3a25a2ed361e4ce621f23f5e642
      description: >-
        The PT-cUSD-23JUL2026 is the asset used as collateral in a Morpho market
        with USDC as the loan token.
    - chainId: 1
      address: '0x606b5c773dc4d6e625c411cf60565f8c30c467d2'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0xc978f01522ff64adafd91856065d602c56e326a0368b895bd9244d5998e60076
      description: >-
        The PT-savUSD-14MAY2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0x606b5c773dc4d6e625c411cf60565f8c30c467d2'
      subtitle: frxUSD
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0xed808d36371491748eaa28b16533cafc270e705139e3ff807ea17ce60d6938c9
      description: >-
        The PT-savUSD-14MAY2026 is the asset used as collateral in a Morpho
        market with frxUSD as the loan token.
    - chainId: 1
      address: '0xd87169640666649f1e6f92034dca9e4ae748de69'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0xca432a8b0f33541cfe164d388823d05b607db43b690d4856f343eec3b42402c0
      description: >-
        The PT-mHYPER-30APR2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0x82b853db31f025858792d8fa969f2a1dc245c179'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0xc2bc5e1e304fb1ea103dcbee37ece3c7e9219fb4b2b19d8ffdf81c39f4fbf180
      description: >-
        The PT-srNUSD-28MAY2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0x9bf45ab47747f4b4dd09b3c2c73953484b4eb375'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0x27b9a0a5bfee98a31eb51e3850250d103a9f8e41673c782defc66aa943af0e65
      description: >-
        The PT-srUSDe-2APR2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0x9bf45ab47747f4b4dd09b3c2c73953484b4eb375'
      subtitle: USDT
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0xb2f87218f0e2478ba7a2b8be9fe76cbd6f54f8654b9651d4bd1f0ea536674691
      description: >-
        The PT-srUSDe-2APR2026 is the asset used as collateral in a Morpho
        market with USDT as the loan token.
    - chainId: 1
      address: '0x6c65db1d88c8eda1e3debf2b2ef3d0ece8600466'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0xb62aac664f81d19f21a158aa0373967ef60fd1ac8de4a9091bd225c007973ca6
      description: >-
        The PT-sNUSD-4JUN2026 is the asset used as collateral in a Morpho market
        with USDC as the loan token.
    - chainId: 8453
      address: '0xc31e19dc6c8a90d628432e15bbd538aa8c789e5d'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/base/market/0xaf2657ed859dcac494afc20ba83e26fa153414da971a1f082ebfcb45d73955f1
      description: >-
        The PT-USDai-18JUN2026-(ARB) is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0x3eaa0f0f0a5d3d595ae4e4b0d27f439d01c3e7b2'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0x9bc98c2f20ac58287ef2c860eea53a2fdc27c17a7817ff1206c0b7840cc7cd79
      description: >-
        The PT-reUSD-25JUN2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 130
      address: '0x9d9874e867b877dd0a3f1eafb8bb1bc54eecc682'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/unichain/market/0x87a686cc100aabe917f8e1ad58140a1b63f0edbb9650a32c0526718dc610b2d5
      description: >-
        The PT-cUSD-23JUL2026-(ETH) is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0x64b393288ab2a0fe7af6b73a9159493e60ab0605'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0x3d353ef0436b85c3b12d53536c19b21c533c046b07c9d92d791a1510e7ef0b74
      description: >-
        The PT-mAPOLLO-30APR2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0xd0609ac13000d88b0bebf5bb21074916edd92bb1'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0x2afd063a5af8e050069cfad4da95c81768b85b140bea2bd89e00407b15ce82c8
      description: >-
        The PT-jrUSDe-2APR2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0x29fd7180e5cced14ad148c7997e6b6857a8be86e'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0x1cfdc0154ae6b9f1887a8250f2582d55606e1a2008e65108fb83dd50a928593e
      description: >-
        The PT-RLP-9APR2026 is the asset used as collateral in a Morpho market
        with USDC as the loan token.
    - chainId: 1
      address: '0x9db38d74a0d29380899ad354121dfb521adb0548'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0x5cebfae10f5e88d33df2421923f3d9f32359429fda2f78edacc9b4fdb09b0553
      description: >-
        The PT-USDG-28MAY2026 is the asset used as collateral in a Morpho market
        with USDC as the loan token.
    - chainId: 1
      address: '0x3de0ff76e8b528c092d47b9dac775931cef80f49'
      subtitle: PYUSD
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0xcb12dcbc7c6c4f20ca1537a3cc1a41ec27501f85a3e322a710d9a16a88a28c0e
      description: >-
        The PT-sUSDE-7MAY2026 is the asset used as collateral in a Morpho market
        with PYUSD as the loan token.
    - chainId: 1
      address: '0xcc16cd49194e7aa3dca780c742580e2f9b418874'
      subtitle: frxUSD
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0x6a8f296524b7f300b56e3653bbfc0ce4dd0dff225f1d5ec09c4fd190886ae53e
      description: >-
        The PT-avUSD-14MAY2026 is the asset used as collateral in a Morpho
        market with frxUSD as the loan token.
    - chainId: 1
      address: '0xcc16cd49194e7aa3dca780c742580e2f9b418874'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0xf80a664057fe3cadcd9e83f27bb1effe5c15d1d2648acc7634daff1581951b5e
      description: >-
        The PT-avUSD-14MAY2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0x2d3c279e5fcdf5b793c0a75ed90738d7369b0b83'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0x2fb3713487c7812e7309935b034f40228841666f6b048faf31fd2110ae674f20
      description: >-
        The PT-stcUSD-23JUL2026 is the asset used as collateral in a Morpho
        market with USDC as the loan token.
    - chainId: 1
      address: '0x5dbf246b37e1b9ac5d08bb38233d71322ae7d166'
      subtitle: USDC
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0xdf034d0351a4c0af947e1a37ecd5ccbce60d72eac90de6fcad48c74e2869d14c
      description: >-
        The PT-iUSD-25JUN2026 is the asset used as collateral in a Morpho market
        with USDC as the loan token.
    - chainId: 1
      address: '0x9bf45ab47747f4b4dd09b3c2c73953484b4eb375'
      subtitle: AUSD
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0xba8c21d3e47814574a61bee82e7053274f731ad253b24865acab8476fa477ee7
      description: >-
        The PT-srUSDe-2APR2026 is the asset used as collateral in a Morpho
        market with AUSD as the loan token.
    - chainId: 1
      address: '0x9db38d74a0d29380899ad354121dfb521adb0548'
      subtitle: AUSD
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0x16f269c5cc745b486060d42e21aef2f33edfe4b8cf6dce95e518a789469aae78
      description: >-
        The PT-USDG-28MAY2026 is the asset used as collateral in a Morpho market
        with AUSD as the loan token.
    - chainId: 1
      address: '0x928fb6ed39100a92b2480f5cbb93453f98d9f4ce'
      subtitle: USDT
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0xfd039edc69eac5eaab4a10463fdbcaca75d6eddb1f0e00248d73fc977fb2554b
      description: >-
        The PT-cUSD-23JUL2026 is the asset used as collateral in a Morpho market
        with USDT as the loan token.
    - chainId: 1
      address: '0x928fb6ed39100a92b2480f5cbb93453f98d9f4ce'
      subtitle: AUSD
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0xe7f998c0ff11ca2bf091d39b6a3cef1035733528187d520c1c47710c8f1acaeb
      description: >-
        The PT-cUSD-23JUL2026 is the asset used as collateral in a Morpho market
        with AUSD as the loan token.
    - chainId: 1
      address: '0x2d3c279e5fcdf5b793c0a75ed90738d7369b0b83'
      subtitle: USDT
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0x5eaaebc81e9e27972ab458811d1b60828e8ab51ef6620f9b3918fd7e68eecec1
      description: >-
        The PT-stcUSD-23JUL2026 is the asset used as collateral in a Morpho
        market with USDT as the loan token.
    - chainId: 1
      address: '0x2d3c279e5fcdf5b793c0a75ed90738d7369b0b83'
      subtitle: AUSD
      integrationUrl: >-
        https://app.morpho.org/ethereum/market/0x54e42432a7c0309ba650080cab6fcff377034fd9de174bbd3a4b519186ffc0f8
      description: >-
        The PT-stcUSD-23JUL2026 is the asset used as collateral in a Morpho
        market with AUSD as the loan token.
  yt: []
  lp: []
