name: Cega
icon: logo.png
category: Yield Strategy
metadata:
  pt: []
  yt:
    - chainId: 1
      address: '0x129e6B5DBC0Ecc12F9e486C5BC9cDF1a6A80bc6A'
      integrationUrl: https://app.cega.fi/products/pendle-etherfi-yt-tiger?product_id=191
      description: Use YT to earn high fixed yields while minimizing potential downside
  lp: []
