name: Upbit
icon: logo.png
category: CEX / Web3 Wallet
url: https://upbit.com/exchange
description: >-
  Upbit is the trusted Digital Asset Exchange for fast and convenient trading experience for professional investors