name: Form
icon: logo.png
metadata:
  pt:
    - chainId: 1
      address: '0xf7906F274c174A52d444175729E3fa98f9bde285'
      integrationUrl: https://meditations.form.network
      description: Deposit PT-ezETH to earn Form Points
  yt: []
  lp: []
