name: Penpie
icon: logo.png
category: Liquid Locker
url: https://www.pendle.magpiexyz.io/stake
description: >-
  Penpie is a next-generation DeFi platform designed to provide Pendle Finance users with yield and veTokenomics boosting services.