name: Marginly
icon: marginly-logo.png
metadata:
  pt:
    - chainId: 1
      address: '0x76F327150224393ff07AAFA3449FBB23103fb279'
      integrationUrl: https://app.marginly.com/mainnet/farm
      description: Highly optimised PT tokens yield farming with up to 10x leverage.
    - chainId: 1
      address: '0xD53A899B731C52Eeb0f9750b6b507e543661D763'
      integrationUrl: https://app.marginly.com/mainnet/farm
      description: Highly optimised PT tokens yield farming with up to 10x leverage.
    - chainId: 1
      address: '0x7aa68E84bCD8d1B4C9e10B1e565DB993f68a3E09'
      integrationUrl: https://app.marginly.com/mainnet/farm
      description: Highly optimised PT tokens yield farming with up to 10x leverage.
  yt: []
  lp: []
