name: Bitget
icon: logo.png
category: CEX / Web3 Wallet
description: >-
  Bitget is a Seychelles-based cryptocurrency exchange that 
  empowers over 20 million users across 100 countries with a focus on copy trading and various smart trading tools.