name: infiniFi
icon: logo.png
category: Yield Strategy
description: infiniFi automates borrow-short, lend-long asset management to achieve superior returns on Pendle PTs without the hassle of manual rollovers.  Higher Yield.  No leverage.
url: https://infinifi.xyz
metadata:
